# Travis-CI build script for Foxxll

language: cpp

sudo: false
dist: trusty

env:
  global:
  - OMP_NUM_THREADS=4
  - TMPDIR=/tmp/
  - FOXXLL_TEST_DISKDIR=$TMPDIR

git:
  depth: 3

matrix:
  include:
  - env: CMAKE_CC="gcc-5"     CMAKE_CXX="g++-5" COMPILER_FLAGS=""       BUILD_TYPE="Release"
    os: linux
    addons: &gcc5
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5

  - env: CMAKE_CC="gcc-5"     CMAKE_CXX="g++-5" COMPILER_FLAGS=""       BUILD_TYPE="RelWithAssert"
    os: linux
    addons: *gcc5

  - env: CMAKE_CC="gcc-7"     CMAKE_CXX="g++-7" COMPILER_FLAGS=""       BUILD_TYPE="Release"
    os: linux
    addons: &gcc7
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7

  - env: CMAKE_CC="gcc-7"     CMAKE_CXX="g++-7" COMPILER_FLAGS=""       BUILD_TYPE="RelWithAssert"
    os: linux
    addons: *gcc7

  - env: CMAKE_CC="clang-4.0" CMAKE_CXX="clang++-4.0" COMPILER_FLAGS="" BUILD_TYPE="RelWithAssert"
    os: linux
    dist: trusty
    addons: &clang40
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0

  - env: CMAKE_CC="clang" CMAKE_CXX="clang++" COMPILER_FLAGS="" BUILD_TYPE="RelWithAssert"
    os: osx

before_script:
  # print out some information
  - df -h

  # configure
  - mkdir build; cd build
  - cmake
      -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
      -DCMAKE_C_COMPILER="$CMAKE_CC" -DCMAKE_CXX_COMPILER="$CMAKE_CXX"
      -DCMAKE_C_FLAGS="$COMPILER_FLAGS" -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS"
      -DFOXXLL_BUILD_TESTS=ON
      -DFOXXLL_TRY_COMPILE_HEADERS=ON
      $CMAKE_ARGS ..

script:
  - make -j4
  - ../misc/travis-run.sh
  - make install
